### ISSUE TITLE
Device Screen Missing on Chrome@50.0.2661.75 (64-bit)

### ISSUE THREAD

**Issue by LearnShare** [openstf/stf#303]
## Current Behavior

Just update Chrome from 49.* to 50.0.2661.75 (64-bit) on OSX 10.11.4, then Device Screen not show up

![image](https://cloud.githubusercontent.com/assets/3265208/14525833/01c0e4a2-0272-11e6-90ec-2b2ba0ce5971.png)

## Possible Solution

Works well on Safari 9.1 (11601.5.17.1) and Vivaldi 1.0.435.40.

Works well on Chrome 41.* and Chrome 49.*.

## Steps to Reproduce (for bugs)

1. Update Chrome to 50.*
2. Open /#!/control/[SN] page
3. You can see it now.

## Your Environment

+ OSX 10.11.4
+ Chrome 50.0.2661.75 (64-bit)
+ STF (latest on npm , and master at 04 Jan, 2016)

Thanks :)

**Comment by sorccu** [comment]
You're right, I just updated and it doesn't work.

**Comment by sorccu** [comment]
Looks like the screen has been abusing display: table-row. It doesn't actually contain any table-cells.

**Comment by sorccu** [comment]
This should be fixed now. Could you build from master and try again?

**Comment by LearnShare** [comment]
@sorccu It works well now 🍻

**Comment by Rabusek** [comment]
I'd rather not open a new issue.. but @sorccu I've updated to specifically that commit (e06b2f2, checked that with npm list stf), but I still get the same exact errors:

Uncaught Error: Unable to read bounds; container must have dimensions

**Comment by sorccu** [comment]
You're probably using prebuilt assets. Run `gulp clean` to always rebuilt assets on run, or `gulp build` to rebuild assets once. You can also use `./node_modules/.bin/gulp <command>` if you don't have gulp installed yet.
