### ISSUE TITLE
Device turns into zombie state

### ISSUE THREAD

**Issue by Zoe1808** [openstf/stf#362]
When i operation one some devices, first few minutes it works fine, but after sometime, the device becomes unworkable, cannot perform any action on it, even can not stop using it.
![image](https://cloud.githubusercontent.com/assets/10767521/16644631/099b471e-4451-11e6-840f-af13335d12fe.png)

The log shows:

INF/provider 3646 [_] Restarting device worker "de6894307ce3"
INF/device:support:push 3693 [de6894307ce3] Sending output to "tcp://127.0.0.1:7116"
INF/device 3693 [de6894307ce3] Preparing device
INF/device:support:sub 3693 [de6894307ce3] Receiving input from "tcp://127.0.0.1:7114"
INF/device:support:sub 3693 [de6894307ce3] Subscribing to permanent channel "_ALL"
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:adb 3693 [de6894307ce3] Waiting for boot to complete
INF/device:support:properties 3693 [de6894307ce3] Loading properties
INF/device:support:abi 3693 [de6894307ce3] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
INF/device:resources:service 3693 [de6894307ce3] Checking whether we need to install STFService
INF/device:resources:service 3693 [de6894307ce3] Running version check
INF/device:resources:service 3693 [de6894307ce3] STFService up to date
INF/device:plugins:service 3693 [de6894307ce3] Launching agent
INF/device:plugins:service 3693 [de6894307ce3] Agent says: "Listening on port 1090"
INF/device:plugins:service 3693 [de6894307ce3] Launching service
INF/device:plugins:service 3693 [de6894307ce3] Agent says: "InputClient started"
FTL/device 3693 [de6894307ce3] Setup had an error TimeoutError: operation timed out
    at afterTimeout (/Users/zy/workspace/stf/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/Users/zy/workspace/stf/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout (timers.js:89:15)
FTL/util:lifecycle 3693 [de6894307ce3] Shutting down due to fatal error
INF/provider 3646 [_] Cleaning up device worker "de6894307ce3"
ERR/provider 3646 [_] Device worker "de6894307ce3" died with code 1

The log keeps printing this infomation, nothing works until i restart the device, pls help!

**Comment by sorccu** [comment]
Don't remove the issue template, now I have to waste time asking you the same questions again.

That particular issue can happen on some devices if frames are not being read from it quickly enough. Which device is it? Please post the output of `adb devices -l`, it contains the necessary details.

**Comment by Zoe1808** [comment]
@sorccu 
sorry, the device is 
de6894307ce3           device usb:336592896X product:land model:Redmi_3S device:land

**Comment by sorccu** [comment]
I don't have that one, but I know that Redmi Note 2 works fine at least.

**Comment by LegendaryBlueShirt** [comment]
I have been experiencing this on all of my Nexus 5 devices running 6.0.1
0697815100eb88eb       device usb:5-2.4.1 product:hammerhead model:Nexus_5 device:hammerhead
06cae874439ca532       device usb:5-2.2 product:hammerhead model:Nexus_5 device:hammerhead

STF is version 2.0.1 and is running using stf local
The scenario is having the control tab open for the device and connected remotely to my system using adb connect.
stf doctor doesn't actually finish running for me

> INF/util:doctor 31156 [*] OS Arch: x64
> INF/util:doctor 31156 [*] OS Platform: linux
> INF/util:doctor 31156 [*] OS Platform: 4.4.0-34-generic
> INF/util:doctor 31156 [*] Using Node 4.2.6
> INF/util:doctor 31156 [*] Using RethinkDB client 2.3.2
> INF/util:doctor 31156 [*] Using ZeroMQ 4.1.5
> INF/util:doctor 31156 [*] Local RethinkDB server 2.3.4~0xenial
> /usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293
>     throw new TypeError('Invalid Version: ' + version);
>     ^
> 
> TypeError: Invalid Version: 2.3.4~0xenial
>     at new SemVer (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:293:11)
>     at Range.test (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1036:15)
>     at Function.satisfies (/usr/local/lib/node_modules/stf/node_modules/semver/semver.js:1085:16)
>     at unsupportedVersion (/usr/local/lib/node_modules/stf/lib/util/doctor.js:13:15)
>     at /usr/local/lib/node_modules/stf/lib/util/doctor.js:95:7
>     at /usr/local/lib/node_modules/stf/lib/util/doctor.js:50:22
>     at ChildProcess.exithandler (child_process.js:204:7)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at maybeClose (internal/child_process.js:821:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at Pipe._onclose (net.js:469:12)

The log is basically this on loop

> FTL/device 31335 [0697815100eb88eb] Setup had an error TimeoutError: operation timed out
>     at afterTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:11:15)
>     at timeoutTimeout (/usr/local/lib/node_modules/stf/node_modules/adbkit/node_modules/bluebird/js/main/timers.js:53:9)
>     at Timer.listOnTimeout (timers.js:92:15)
> FTL/util:lifecycle 31335 [0697815100eb88eb] Shutting down due to fatal error
> INF/provider 9924 [*] Cleaning up device worker "0697815100eb88eb"
> ERR/provider 9924 [*] Device worker "0697815100eb88eb" died with code 1
> INF/provider 9924 [*] Restarting device worker "0697815100eb88eb"
> INF/device:support:adb 31346 [06cae874439ca532] Waiting for boot to complete
> INF/device:support:push 31357 [0697815100eb88eb] Sending output to "tcp://127.0.0.1:7116"
> INF/device 31357 [0697815100eb88eb] Preparing device
> INF/device:support:sub 31357 [0697815100eb88eb] Receiving input from "tcp://127.0.0.1:7114"
> INF/device:support:sub 31357 [0697815100eb88eb] Subscribing to permanent channel "*ALL"
> INF/device:support:adb 31346 [06cae874439ca532] Waiting for boot to complete
> INF/device:support:adb 31357 [0697815100eb88eb] Waiting for boot to complete
> INF/device:support:adb 31346 [06cae874439ca532] Waiting for boot to complete

**Comment by vdelendik** [comment]
There is hardcoded timeout for boot operation in <STF_HOME>/lib/units/device/support/adb.js
And if in your pool there is slow device you will receive this exception every time after its reboot.
Sometimes it crashes everything in our case and only failover service returns STF back to normal state.
So we increased default timeout on line #25 to resolve this issue:
        .timeout(5*60000)

**Comment by sorccu** [comment]
That sounds weird, but I've now made the timeout configurable in https://github.com/openstf/stf/commit/72a16ed2ff559d1ea895c0213fa805c140b5948a.

**Comment by Zoe1808** [comment]
@vdelendik I've tried to increase the default timeout to 5*60000, but it's still not working... The device is still in 'zombie state' and the log keeps printing the same error.

**Comment by sorccu** [comment]
Could be the same as #100. For usage of `ZMQ_TCP_KEEPALIVE` and `ZMQ_TCP_KEEPALIVE_IDLE` see https://github.com/openstf/stf/pull/104#issuecomment-149859430.

Note that the message can also imply that you have too many devices connected on that machine, or that the device isn't receiving enough power. It can be caused by many things.

**Comment by Zoe1808** [comment]
ZMQ_TCP_KEEPALIVE and ZMQ_TCP_KEEPALIVE_IDLE setting is NOT working...

I've tried to figure out what causes this timeout, it turns out to be the code 
`devutil.waitForPort(adb, options.serial, service.port).timeout(15000)`
I've tried to increased the timeout to 15000*5, but still the same.

And I also found out that at this moment, the adb command of this device becomes **very very very** slow( adb -s SERIAL shell), almost not responding, maybe this is what causes the timeout.

The problem now is WHAT may be the reason that causes adb command of the device slow?

**Comment by sorccu** [comment]
Do you have USB tethering or personal hotspot enabled on that device?

**Comment by Zoe1808** [comment]
@sorccu no, and this error seems only happens on Android 6.0.1.

**Comment by sorccu** [comment]
Note that the current codebase does not have `waitForPort` anywhere anymore. Try using the latest version of STF and let us know if anything changes.

**Comment by Zoe1808** [comment]
@sorccu The latest version of STF works fine! The device remains stable for a long time till now.

**Comment by sorccu** [comment]
Seems that this issue was resolved. Closing. Thanks!

**Comment by metallious** [comment]
This is still happening on some custom rockchip rk3288 device.

How to reproduce:
- turn screen off
- stop using device
- start using device again
- turn screen on
- device will crash

This also happens randomly while using the device

Can you please give me a hint on why is this happening? I want to investigate the issue further.

device logs
```
07-09 10:57:36.401  7099  7118 I STFSetWakeLockResponder: Acquiring wake lock
07-09 10:57:36.406  5556  6358 I PowerManagerService: Waking up from sleep (uid 10118)...
07-09 10:57:36.431  5556  5589 I DisplayPowerController: Blocking screen on until initial contents have been drawn.
07-09 10:57:36.834   176   176 D Surface : Surface::final mReqUsage=203
07-09 10:57:36.835   176   176 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
07-09 10:57:36.839   176   176 D gralloc : Isfb=0, [574,359,576,2304], fmt=1, byte_stride=2304
07-09 10:57:36.853   176   176 D gralloc : Isfb=0, [574,359,576,2304], fmt=1, byte_stride=2304
07-09 10:57:55.939   176   176 W mali_winsys: native_window_api_disconnect failed: -32
07-09 10:57:55.940   176   176 W libEGL  : EGLNativeWindowType 0xb7846dd8 disconnect failed
07-09 10:57:56.126   176   176 D Surface : Surface::final mReqUsage=203
07-09 10:57:56.127   176   176 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
07-09 10:57:56.131   176   176 D gralloc : Isfb=0, [979,612,992,3968], fmt=1, byte_stride=3968
07-09 10:57:56.152   176   176 D gralloc : Isfb=0, [979,612,992,3968], fmt=1, byte_stride=3968
07-09 10:58:01.707  5556  6317 I Process : Sending signal. PID: 5556 SIG: 3
07-09 10:58:01.709  5556  5560 I art     : Thread[2,tid=5560,WaitingInMainSignalCatcherLoop,Thread*=0xb8476278,peer=0x12c010a0,"Signal Catcher"]: reacting to signal 3
07-09 10:58:02.265  5556  5897 E SensorsHal: poll() failed (Interrupted system call)
07-09 10:58:04.749  5556  5560 I art     : Wrote stack traces to '/data/anr/traces.txt'
07-09 10:58:37.024  5556  6317 I Process : Sending signal. PID: 5556 SIG: 3
07-09 10:58:37.025  5556  5560 I art     : Thread[2,tid=5560,WaitingInMainSignalCatcherLoop,Thread*=0xb8476278,peer=0x12c010a0,"Signal Catcher"]: reacting to signal 3
07-09 10:58:37.440  5556  5897 E SensorsHal: poll() failed (Interrupted system call)
07-09 10:58:39.764  5556  5560 I art     : Wrote stack traces to '/data/anr/traces.txt'
07-09 10:58:44.726  5556  6317 I Watchdog_N: dumpKernelStacks
07-09 10:58:44.822  5556  6317 W Watchdog: *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in monitor com.android.server.am.ActivityManagerService on foreground thread (android.fg), Blocked in handler on ui thread (android.ui), Blocked in handler on display thread (android.display), Blocked in handler on ActivityManager (ActivityManager)
07-09 10:58:44.822  5556  6317 W Watchdog: foreground thread stack trace:
07-09 10:58:44.823  5556  6317 W Watchdog:     at com.android.server.am.ActivityManagerService.monitor(ActivityManagerService.java:20035)
07-09 10:58:44.823  5556  6317 W Watchdog:     at com.android.server.Watchdog$HandlerChecker.run(Watchdog.java:172)
07-09 10:58:44.823  5556  6317 W Watchdog:     at android.os.Handler.handleCallback(Handler.java:743)
07-09 10:58:44.823  5556  6317 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 10:58:44.823  5556  6317 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
07-09 10:58:44.823  5556  6317 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 10:58:44.823  5556  6317 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-09 10:58:44.823  5556  6317 W Watchdog: ui thread stack trace:
07-09 10:58:44.824  5556  6317 W Watchdog:     at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:17263)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.app.ContextImpl.sendBroadcast(ContextImpl.java:767)
07-09 10:58:44.824  5556  6317 W Watchdog:     at com.android.server.policy.PhoneWindowManager.updateSettings(PhoneWindowManager.java:1786)
07-09 10:58:44.824  5556  6317 W Watchdog:     at com.android.server.policy.PhoneWindowManager$SettingsObserver.onChange(PhoneWindowManager.java:750)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.database.ContentObserver.onChange(ContentObserver.java:130)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.database.ContentObserver.onChange(ContentObserver.java:145)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.os.Handler.handleCallback(Handler.java:743)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
07-09 10:58:44.824  5556  6317 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 10:58:44.824  5556  6317 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-09 10:58:44.824  5556  6317 W Watchdog: display thread stack trace:
07-09 10:58:44.825  5556  6317 W Watchdog:     at com.android.server.wm.WindowManagerService.requestTraversal(WindowManagerService.java:10671)
07-09 10:58:44.825  5556  6317 W Watchdog:     at com.android.server.wm.WindowManagerService$LocalService.requestTraversalFromDisplayManager(WindowManagerService.java:12082)
07-09 10:58:44.825  5556  6317 W Watchdog:     at com.android.server.display.DisplayManagerService$DisplayManagerHandler.handleMessage(DisplayManagerService.java:1103)
07-09 10:58:44.825  5556  6317 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-09 10:58:44.825  5556  6317 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
07-09 10:58:44.825  5556  6317 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 10:58:44.825  5556  6317 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-09 10:58:44.825  5556  6317 W Watchdog: ActivityManager stack trace:
07-09 10:58:44.827  5556  6317 W Watchdog:     at com.android.server.am.ActivityStackSupervisor.handleDisplayChanged(ActivityStackSupervisor.java:3787)
07-09 10:58:44.827  5556  6317 W Watchdog:     at com.android.server.am.ActivityStackSupervisor.-wrap3(ActivityStackSupervisor.java)
07-09 10:58:44.827  5556  6317 W Watchdog:     at com.android.server.am.ActivityStackSupervisor$ActivityStackSupervisorHandler.handleMessage(ActivityStackSupervisor.java:4077)
07-09 10:58:44.827  5556  6317 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-09 10:58:44.827  5556  6317 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
07-09 10:58:44.827  5556  6317 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-09 10:58:44.827  5556  6317 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-09 10:58:44.827  5556  6317 W Watchdog: *** GOODBYE!
07-09 10:58:44.827  5556  6317 I Process : Sending signal. PID: 5556 SIG: 9
07-09 10:58:45.181   211   211 E installd: eof
07-09 10:58:45.181   211   211 E installd: failed to read size
07-09 10:58:45.181   211   211 I installd: closing connection
07-09 10:58:45.188   176   176 D SurfaceFlinger: Set power mode=2, type=0 flinger=0xb77b6df0
07-09 10:58:45.188   176   176 I hwcomposer: hwc_blank dpy[0],blank[0]
07-09 10:58:45.191  7099 11129 E WifiManager: Channel connection lost
07-09 10:58:45.193  5974  6207 E WifiManager: Channel connection lost
07-09 10:58:45.198  9505  9557 W Sensors : sensorservice died [0xb86e98f8]
07-09 10:58:45.199   174   174 I ServiceManager: service 'content' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'permission' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'media.camera.proxy' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'wifi' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'power' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'alarm' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'battery' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'batterystats' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'appops' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'deviceidle' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'cpuinfo' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'scheduling_policy' died
07-09 10:58:45.199   174   174 I ServiceManager: service 'procstats' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'window' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'bluetooth_manager' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'gfxinfo' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'mount' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'ethernet' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'consumer_ir' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'user' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'meminfo' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'display' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'sensorservice' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'textservices' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'telephony.registry' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'processinfo' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'account' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'media_router' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'usagestats' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'clipboard' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'vibrator' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'dbinfo' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'webviewupdate' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'activity' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'lock_settings' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'uimode' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'package' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'wifip2p' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'dropbox' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'netpolicy' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'network_score' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'input' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'netstats' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'input_method' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'accessibility' died
07-09 10:58:45.200   174   174 I ServiceManager: service 'serial' died
07-09 10:58:45.200  9505  9531 E WifiManager: Channel connection lost
07-09 10:58:45.201   174   174 I ServiceManager: service 'jobscheduler' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'wifiscanner' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'search' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'backup' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'connectivity' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'rttmanager' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'device_policy' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'network_management' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'country_detector' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'DockObserver' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'usb' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'devicestoragemonitor' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'updatelock' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'location' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'restrictions' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'media_session' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'statusbar' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'servicediscovery' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'samplingprofiler' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'appwidget' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'wallpaper' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'graphicsstats' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'audio' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'trust' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'notification' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'media_projection' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'commontime_management' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'voiceinteraction' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'diskstats' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'fingerprint' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'launcherapps' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'imms' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'display_device_management' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'assetatlas' died
07-09 10:58:45.201   174   174 I ServiceManager: service 'print' died
07-09 10:58:45.202   174   174 I ServiceManager: service 'dreams' died
07-09 10:58:45.202  5374  5405 W AudioFlinger: power manager service died !!!
07-09 10:58:45.203  6211  6406 E WifiManager: Channel connection lost
07-09 10:58:45.209  5974  5974 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-09 10:58:45.210  5974  5974 E AndroidRuntime: FATAL EXCEPTION: main
07-09 10:58:45.210  5974  5974 E AndroidRuntime: Process: com.android.systemui, PID: 5974
07-09 10:58:45.210  5974  5974 E AndroidRuntime: java.lang.RuntimeException: Failure from system
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:931)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:464)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.recents.Recents.hideRecentsInternal(Recents.java:347)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.recents.Recents.hideRecents(Recents.java:330)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.statusbar.BaseStatusBar.hideRecents(BaseStatusBar.java:1126)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.hideRecents(PhoneStatusBar.java:4213)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.statusbar.BaseStatusBar$H.handleMessage(BaseStatusBar.java:1236)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar$H.handleMessage(PhoneStatusBar.java:2256)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: Caused by: android.os.DeadObjectException
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3055)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:927)
07-09 10:58:45.210  5974  5974 E AndroidRuntime: 	... 13 more
07-09 10:58:45.211  5974  5974 E AndroidRuntime: Error reporting crash
07-09 10:58:45.211  5974  5974 E AndroidRuntime: android.os.DeadObjectException
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
07-09 10:58:45.211  5974  5974 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```
