### ISSUE TITLE
Mobile screen no more refreshed after downloading file through 'File explorer' feature

### ISSUE THREAD

**Issue by denis99999** [openstf/stf#612]
Lastest release used.

All works well except the below issue:

When a device is under control through the GUI, if I download a file using the 'File Explorer' window (i.e. picture in sdcard/DCIM/Camera), then the mobile screen freeze so that it becomes impossible to interact with it, until I globally refresh the brower window.

**Comment by sorccu** [comment]
Latest release or github master?

**Comment by denis99999** [comment]
I used the docker hub images

**Comment by sorccu** [comment]
Ok. So when you create issues, there's an issue template that contains the
information we want. For example, it could be an issue with your device. Or
you could have an error in the log output. The template covers those
issues. Please fill in the whole template if you need assistance.

**Comment by denis99999** [comment]
**What is the issue or idea you have?**
Lastest release used, I use your official docker image available from docker hub.

All work well except the below issue:

When a device is under control through the GUI, if I download a file using the 'File Explorer' window (i.e. picture in sdcard/DCIM/...), then the mobile screen freezes so that it becomes impossible to interact with it, until I globally refresh the browser window.

Note I detected this issue from many months but as it was not blocking I did not spend time to report it, now I have time so I post it.

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**
all devices are concerned, I have 18 devices in my test platform : sony, samsung, huawei, htc, lg, 

root@debian:/home/debian# adb devices -l
List of devices attached
BH906ZJG56             device usb:1-2 product:F5121 model:F5121 device:F5121


**Please provide the steps to reproduce the issue.**
1/ take the control of a device
2/ take a picture using the camera
3/ go to the file explorer view
4/ select for download this picture in sdcard/DCIM/...
5/ at this time it is no more possible to interact with the device through the GUI, for example the device screen is like frozen

Then, I have to refresh the STF window of my internet browser to get back the control of the device.

**What is the expected behavior?**
I should be able to continue to interact normally with the device through the GUI, without the need to refresh globally STF window of my internet browser

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**
yes, the minicap service is stopped when the download action is fired:

`Jun  7 14:28:01 debian docker[1635]: INF/device:plugins:filesystem 120 [BH906ZJG56] Retrieving file "/sdcard/DCIM/100ANDRO/DSC_0001.JPG"
Jun  7 14:28:05 debian docker[1635]: INF/storage:temp 67 [*] Uploaded "DSC_0001.JPG" to "/tmp/upload_b8f3ec5a4855edb22d0795185d858214"
Jun  7 14:28:05 debian docker[1635]: INF/device:support:storage 120 [BH906ZJG56] Uploaded to "/s/blob/43b9004f-c0dd-4f39-9fec-6c6071deb6c1/DSC_0001.JPG"
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] Requesting frame producer to stop
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] Disconnecting from minicap service
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] Stopping minicap service
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] Sending SIGTERM to minicap
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] minicap says: "INFO: (jni/minicap/minicap.cpp:197) Received SIGTERM, stopping"
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] minicap says: "INFO: (jni/minicap/minicap.cpp:516) Closing client connection"
Jun  7 14:28:05 debian docker[1635]: INF/device:plugins:screen:stream 120 [BH906ZJG56] minicap says: "INFO: (external/MY_minicap/src/minicap_23.cpp:284) Destroying virtual display"
`

**Please run `stf doctor` and paste the output here.**
```
root@debian:/home/debian# docker exec -t -i 87329623209c stf doctor
INF/util:doctor 148 [*] OS Arch: x64
INF/util:doctor 148 [*] OS Platform: linux
INF/util:doctor 148 [*] OS Platform: 3.16.0-4-amd64
INF/util:doctor 148 [*] Using Node 6.9.5
INF/util:doctor 148 [*] Using RethinkDB client 2.3.3
INF/util:doctor 148 [*] Using ZeroMQ 4.1.4
WRN/util:doctor 148 [*] Executable was not found
WRN/util:doctor 148 [*] Executable was not found
WRN/util:doctor 148 [*] Executable was not found
INF/util:doctor 148 [*] GraphicsMagick 1.3.23
```

**Comment by thinkhy** [comment]
I hit the same problem for several times. I'll  post device info and log when the problem reoccur.

**Comment by vbanthia** [comment]
This is an old issue and there is a PR for this https://github.com/openstf/stf/pull/186

@gunta 
I think, we should just merge the above PR.

**Comment by vbanthia** [comment]
Fixed in https://github.com/openstf/stf/pull/186

**Comment by denis99999** [comment]
Hi,
I verified your #186 fix works well with Chrome and Safari but with Firefox (version 54.0 64 bit) this issue remains !
